name: Update YML

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate catalog
        run: python parser.py

      - name: Commit catalog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add catalog.yml
          git commit -m "Update catalog" || exit 0
          git push
